apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: default
  labels:
    app: web-server
    monitoring: http-metrics
spec:
  selector:
    app: web-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    
    - name: metrics
      port: 80
      targetPort: 8080
