apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        monitoring: http-metrics
    spec:
      containers:
      - name: api
        image: 149536499628.dkr.ecr.eu-west-3.amazonaws.com/api:dashboard-for-microservices
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 3030
        env:
        - name: DB_URL
          value: postgres.justalternate-eks-cluster.internal
        - name: DB_NAME
          value: my_postgres
        - name: DB_USERNAME
          value: username
        - name: DB_PASSWORD
          value: password
        startupProbe:
          httpGet:
            path: /liveness
            port: web
          failureThreshold: 2
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /liveness
            port: web
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: web
          periodSeconds: 5
